version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    command: yarn dev --port=3001
    environment:
      - NODE_ENV=development
